# Generated by Django 4.2.5 on 2023-09-09 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('adamId', models.CharField(blank=True, max_length=50, null=True)),
                ('bundle_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('identifier', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('campaign_id', models.CharField(blank=True, max_length=50, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('serving_status', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('modification_time', models.DateTimeField(blank=True, null=True)),
                ('total_budget', models.FloatField(default=0, null=True)),
                ('daily_budget', models.FloatField(default=0, null=True)),
                ('display_status', models.CharField(blank=True, max_length=50, null=True)),
                ('supply_sources', models.CharField(blank=True, max_length=500, null=True)),
                ('add_channel_type', models.CharField(blank=True, max_length=50, null=True)),
                ('org_id', models.CharField(blank=True, max_length=20, null=True)),
                ('billing_event', models.CharField(blank=True, max_length=50, null=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.app')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganicUserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('data', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserSubscriptionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('subscription_id', models.CharField(blank=True, max_length=20, null=True)),
                ('subscription_status', models.CharField(blank=True, max_length=20, null=True)),
                ('device_time', models.DateTimeField(blank=True, null=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.app')),
                ('app_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.appuser')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_subscription_events', to='campaign.campaign')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserConversionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('org_id', models.CharField(blank=True, max_length=20, null=True)),
                ('keyword_id', models.CharField(blank=True, max_length=20, null=True)),
                ('ad_id', models.CharField(blank=True, max_length=20, null=True)),
                ('ad_group_id', models.CharField(blank=True, max_length=20, null=True)),
                ('conversion_type', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=20, null=True)),
                ('ad_click_date', models.DateTimeField(blank=True, null=True)),
                ('attribution', models.BooleanField(default=True)),
                ('device_time', models.DateTimeField(blank=True, null=True)),
                ('device_type', models.CharField(blank=True, max_length=20, null=True)),
                ('os_version', models.CharField(blank=True, max_length=20, null=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.app')),
                ('app_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.appuser')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.campaign')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
