# Generated by Django 4.2.5 on 2023-09-11 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('data_type', models.CharField(blank=True, choices=[('CM', 'Campaign'), ('KW', 'Keyword'), ('AG', 'Ad Group'), ('ST', 'Search Term'), ('AD', 'Ad')], max_length=20, null=True)),
                ('impressions', models.IntegerField(default=0)),
                ('taps', models.IntegerField(default=0)),
                ('installs', models.IntegerField(default=0)),
                ('new_downloads', models.IntegerField(default=0)),
                ('re_downloads', models.IntegerField(default=0)),
                ('lat_on_installs', models.IntegerField(default=0)),
                ('lat_off_installs', models.IntegerField(default=0)),
                ('ttr', models.FloatField(default=0)),
                ('avg_cpa', models.FloatField(default=0)),
                ('avg_cpt', models.FloatField(default=0)),
                ('avg_cpm', models.FloatField(default=0)),
                ('local_spend', models.FloatField(default=0)),
                ('conversion_rate', models.FloatField(default=0)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
