# Generated by Django 4.2.5 on 2023-12-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_bulkuserdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkuserdata',
            name='user_identifier',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
