# Generated by Django 4.2.5 on 2024-01-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_bulkuserdata_user_identifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkAttributionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user_identifier', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('data', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
