# Generated by Django 4.2.5 on 2024-02-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0005_userconversionevent_app_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscriptionevent',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usersubscriptionevent',
            name='subscription_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
